index.md

Homepage banner upload

---

_about-us/School Services.md

Hazliana,
Need to update the uniform

Update the uniform vendor

---

_mk-fengshan/MK Fengshan.md

Hi Haz,
Please approve the waitlist link for MK Fengshan page.
Thank you boss!

Update MK Fengshan Waitlist Link

---

_about-us/School Services.md

Help to update the dental school updates

Update of School Dental

---

_about-us/School Services.md
index.md

Updates for school vendor and website site notifications

Update on school uniform services and notifications

---

_fengshan-family/Exco Members.md
_links/For Parents.md

Update file: For Parents.md

---

_fengshan-family/Exco Members.md
_fengshan-family/Partnership/SAC.md
_links/For Parents.md

edit the SAC committee and EXCO page

SAC Committee and EXCO Edit

---

_links/For Staff.md

change the link in the staff link

to perform change

---

_links/For Staff.md
index.md

To correct error in the hyperlink in the staff link page

To correct error

---

_data/navigation.yml
_test/Announcements.md
_test/collection.yml
pages/Announcements.md

Music Learning @ Fengshan

---

index.md

Approve the list

---

_about-us/School Canteen Opening.md
index.md

To delete hompage infopic for HBL and canteen advertisement

Delete the homepage canteen ad and HBL

---

_config.yml
_links/For Parents.md
_links/For Pupils.md
index.md

Parents Gateway App Link and user guide

---

_departments/ICT/ICT.md
_links/For Parents.md
_mk-fengshan/MK Fengshan.md
_programmes/MOE’s Sexuality Education.md

MK Fengshan, MOE Sexuality Education and IT Dept list

---

_mk-fengshan/MK Fengshan.md

Changes to the waistlist guide and link

MK waitlist guide and link

---

_mk-fengshan/MK Fengshan.md

MK Fengshan waiting list update

---

_about-us/School Canteen Opening.md
_about-us/School Virtual Tour.md
_about-us/collection.yml
index.md

Removal of Viritual Tour and Canteen Opening

---

_links/For Pupils.md

Fengshan Haven link

---

_about-us/Hall of Fame/2024.md
_cca/Clubs and Societies.md
_cca/Physical Sports.md
_cca/Uniformed Groups.md
_cca/Visual and Performing Arts.md
_fengshan-family/Exco Members.md

Updates CCA site

---

_mk-fengshan/Our Staff at MK.md

remove the photos and replace with the table view

MK Staff edit

---

_cca/Clubs and Societies.md
_cca/Physical Sports.md
_cca/Uniformed Groups.md
_cca/Visual and Performing Arts.md
_departments/Physical Education/PE Overview.md
_mk-fengshan/MK Orientation Day.md

Edit School Website

---

index.md

School website HBL link for P1-P6.

Submit review
